import { Nuxt } from '@nuxt/schema/dist/index'
import { addTemplate } from '@nuxt/kit'

export const saveGeneratedFile = (nuxt: Nuxt, iconNames: string[] | null) => {
  addTemplate({
    filename: 'nuxt-icons.d.ts',
    getContents: () => {
      return `// @ts-nocheck
// eslint-disable
/** 
 * ---------------------------------------------------
 * 🚗 Generated by nuxt-icons. Do not modify !
 * ---------------------------------------------------
 * */

declare module '#app' {
  type NuxtIconName = ${iconNames === null ? 'string' : iconNames.map(p => `"${p.replace(/[\\"]/g, '\\$&')}"`).join(' | ')}
}
`
    }
  })
}
